jobs:
  test_0:
    name: test_0
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: pip install each
      - run: ls -x1 tests | grep "^0_" > testlist
      - run: docker build --build-arg CONTAINERTEST=1 -f Container-8.test -t centos_stream_8_sigt_f . 
      - run: "docker run -d --name test8 --privileged --rm -e CONTAINERTEST=1 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/opt centos_stream_8_sigt_f"
      - run: each -j 4 --no-stdin testlist "docker exec --privileged -e CONTAINERTEST=1  test8 sh -c 'cd /opt && ./runtests.sh {}'"
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \;
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \; > failed_tests
      - run: cat failed_tests | grep -v "^1" | xargs -i tail {}/out
      - run: "! [[ -s failed_tests ]]"
  test_pxaa:
    name: test_pxaa
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: pip install each
      - run: ls -x1 tests | grep "^p_" > testlist
      - run: split -l45 testlist
      - run: docker build --build-arg CONTAINERTEST=1 -f Container-8.test -t centos_stream_8_sigt_f . 
      - run: "docker run -d --name test8 --privileged --rm -e CONTAINERTEST=1 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/opt centos_stream_8_sigt_f"
      - run: each -j 4 --no-stdin xaa "docker exec --privileged -e CONTAINERTEST=1  test8 sh -c 'cd /opt && ./runtests.sh {}'"
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \;
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \; > failed_tests
      - run: cat failed_tests | grep -v "^1" | xargs -i tail {}/out
      - run: "! [[ -s failed_tests ]]"
  test_pxab:
    name: test_pxab
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: pip install each
      - run: ls -x1 tests | grep "^p_" > testlist
      - run: split -l45 testlist
      - run: docker build --build-arg CONTAINERTEST=1 -f Container-8.test -t centos_stream_8_sigt_f . 
      - run: "docker run -d --name test8 --privileged --rm -e CONTAINERTEST=1 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/opt centos_stream_8_sigt_f"
      - run: each -j 4 --no-stdin xab "docker exec --privileged -e CONTAINERTEST=1  test8 sh -c 'cd /opt && ./runtests.sh {}'"
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \;
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \; > failed_tests
      - run: cat failed_tests | grep -v "^1" | xargs -i tail {}/out
      - run: "! [[ -s failed_tests ]]"
  test_pxac:
    name: test_pxac
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: pip install each
      - run: ls -x1 tests | grep "^p_" > testlist
      - run: split -l45 testlist
      - run: docker build --build-arg CONTAINERTEST=1 -f Container-8.test -t centos_stream_8_sigt_f . 
      - run: "docker run -d --name test8 --privileged --rm -e CONTAINERTEST=1 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/opt centos_stream_8_sigt_f"
      - run: each -j 4 --no-stdin xac "docker exec --privileged -e CONTAINERTEST=1  test8 sh -c 'cd /opt && ./runtests.sh {}'"
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \;
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \; > failed_tests
      - run: cat failed_tests | grep -v "^1" | xargs -i tail {}/out
      - run: "! [[ -s failed_tests ]]"
  test_r:
    name: test_r
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: pip install each
      - run: ls -x1 tests | grep "^r_" > testlist
      - run: docker build --build-arg CONTAINERTEST=1 -f Container-8.test -t centos_stream_8_sigt_f . 
      - run: "docker run -d --name test8 --privileged --rm -e CONTAINERTEST=1 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/opt centos_stream_8_sigt_f"
      - run: each -j 4 --no-stdin testlist "docker exec --privileged -e CONTAINERTEST=1  test8 sh -c 'cd /opt && ./runtests.sh {}'"
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \;
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \; > failed_tests
      - run: cat failed_tests | grep -v "^1" | xargs -i tail {}/out
      - run: "! [[ -s failed_tests ]]"
  test_z:
    name: test_z
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: pip install each
      - run: ls -x1 tests | grep "^z_" > testlist
      - run: docker build --build-arg CONTAINERTEST=1 -f Container-8.test -t centos_stream_8_sigt_f . 
      - run: "docker run -d --name test8 --privileged --rm -e CONTAINERTEST=1 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/opt centos_stream_8_sigt_f"
      - run: each -j 4 --no-stdin testlist "docker exec --privileged -e CONTAINERTEST=1  test8 sh -c 'cd /opt && ./runtests.sh {}'"
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \;
      - run: find . -type f -name "status" -exec grep '1' "{}" \; -exec dirname "{}" \; > failed_tests
      - run: cat failed_tests | grep -v "^1" | xargs -i tail {}/out
      - run: "! [[ -s failed_tests ]]"  
name: Greeting
on:
  push: {}
